### ISSUE TITLE
FAQ ".../jre/bin/java: not found" broken link

### ISSUE THREAD

**Issue by YozhEzhi** [SonarSource/sonar-scanner-npm#107]
[This link](https://laptrinhx.com/docker-for-mac-alpine-glibc-issues-802275018) seems not working now.

Could you please make (gist?) link with workaround?

**Comment by vdiez** [comment]
can you please clarify what is the problem?  I cannot access the web you are referencing to and that domain is not under our control

**Comment by YozhEzhi** [comment]
Sorry. I'm talking about link from FAQ in README. 
https://github.com/SonarSource/sonar-scanner-npm/blob/master/README.md#in-my-docker-container-the-scanner-fails-with-jrebinjava-not-found-how-do-i-solve-this

**Comment by vdiez** [comment]
Hi @YozhEzhi , sorry for the late reply. are you using Linux Alpine?

**Comment by YozhEzhi** [comment]
@vdiez Hi! Yes, I am.

**Comment by vdiez** [comment]
You have multiple options:
* Install gcc on Alpine. Running `apk add build-base` [should be enough](https://wiki.alpinelinux.org/wiki/GCC).
* Use the scanner docker image. Available [here](https://hub.docker.com/r/sonarsource/sonar-scanner-cli)
* If you have your own Java binaries available in the PATH, modify the shell script on the cached scanner (usually under `~/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner`). Modify line 42 from:
```
use_embedded_jre=true
```

to 

```
use_embedded_jre=false
```

**Comment by YozhEzhi** [comment]
Thank you! I will try this options later.

**Comment by vdiez** [comment]
Closing this, feel free to report back in [our community](https://community.sonarsource.com/) (Github issues have been closed) if you are encountering further issues.
