### ISSUE TITLE
Custom scanner from CLI

### ISSUE THREAD

**Issue by black444** [SonarSource/sonar-scanner-npm#168]
Hi,

Is there a possibility to set custom scanner from CLI?

We scan node projects in separate stage on Jenkins, so we have to use `npx sonarqube-scanner` command. Our container image contains already pre-installed `sonar-scanner-cli` and `sonar-scanner-npm` library (nodes have no internet access).
It looks like code logic do not check if `sonar-scanner-cli` already exists, just tries to download it.
https://github.com/SonarSource/sonar-scanner-npm/blob/e06fd72f81f4c44bf068d695aa6cffd9ab3b4a08/src/scan.ts#L73

In readme there is information to set custom scanner in code, however I don't know how to do it from CLI.

**Comment by 7PH** [comment]
Hello @black444 , you are correct, this is a limitation that I think we should address. I've created [a ticket](https://sonarsource.atlassian.net/browse/SCANNPM-48) to track the work required to support this use-case, thanks!
