### ISSUE TITLE
[Security] Vulnerable library brought in -> decompress-tar@4.1.1 #569

### ISSUE THREAD

**Issue by mlawrence999** [SonarSource/sonar-scanner-npm#32]
Seems the latest version of sonarqube-scanner (3.0.0) ends up bringing in the vulnerable library decompress-tar@4.1.1. More details about this vulnerability here - https://security.snyk.io/package/npm/decompress-tar

The complete dependency tree is:

dependencies:
sonarqube-scanner 3.0.0
└─┬ decompress 4.2.1
  ├── decompress-tar 4.1.1
  ├─┬ decompress-tarbz2 4.1.1
  │ └── decompress-tar 4.1.1
  └─┬ decompress-targz 4.1.1
    └── decompress-tar 4.1.1

Please consider changing the dependency tree so decompress-tar@4.1.1 is not used

**Comment by ilia-kebets-sonarsource** [comment]
Hello @mlawrence999,

Thank you for the heads up, we'll update this dependency shortly.
