### ISSUE TITLE
Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by Mikilll94** [SonarSource/sonar-scanner-npm#41]
I am getting this error when running `node sonar-config.js`

```
Error: Cannot find module 'mkdirp'
```

**Comment by ilia-kebets-sonarsource** [comment]
Hello @Mikilll94,

`mkdirp` is a new dependency, can you fetch them using `npm i` and try again?

**Comment by Mikilll94** [comment]
Updating to the latest version of `sonar-scanner-npm` fixed the issue.
