### ISSUE TITLE
[Question] It is possible to have diferent return codes if the quality gate fails?

### ISSUE THREAD

**Issue by ciandt-crodrigues** [SonarSource/sonar-scanner-npm#46]
It is possible to have diferent return codes if the quality gate fails?
I'm trying to use this on Github Actions and would like to fail if the quality gate fails.

**Comment by victor-diez-sonarsource** [comment]
Sorry, we will not implement this, the SonarQube Github action already takes into account the quality gate result. Scanner return codes should be used for that.
