### ISSUE TITLE
Acuasec vulnerabilities

### ISSUE THREAD

**Issue by alexvarelaAA** [SonarSource/sonar-scanner-npm#48]
According with the reports from Aquasec you library contains vulnerabilities in these dependencies. 

Solutions:

- Upgrade package ansi-regex to version 5.0.1 or above.
- Upgrade package browserslist to version 4.16.5 or above.
- Upgrade package express to version 4.17.3 or above.
- Upgrade package glob-parent to version 5.1.2 or above.
- Upgrade package glob-parent to version 6.0.1 or above.
- Upgrade package hosted-git-info to version 2.8.9 or above.
- Upgrade package json5 to version 2.2.2 or above.
- Upgrade package minimatch to version 3.0.5 or above.
- Upgrade package minimist to version 1.2.6 or above.
- Upgrade package path-parse to version 1.0.7 or above.
- Upgrade package postcss to version 7.0.36 or above.
- Upgrade package qs to version 6.7.3 or above.
- Upgrade package semver to version 7.5.2 or above.
- Upgrade package trim-newlines to version 3.0.1 or above.

All these looks line are under nested dependencies of .scannerwork/css-bundle/node_modules.

**Comment by victor-diez-sonarsource** [comment]
Thanks, we'll have a look before next release

**Comment by victor-diez-sonarsource** [comment]
Closing, those dependencies are not from the this package, but from SonarJS. When running a scan, SonarJS will be deployed under that path.
