### ISSUE TITLE
ERROR: impossible to download and extract binary: fileType is not a function

### ISSUE THREAD

**Issue by alexvarelaAA** [SonarSource/sonar-scanner-npm#49]
I'm getting a error that `ERROR: impossible to download and extract binary: fileType is not a function` this happened after I upgrade 

"file-type": "^16.5.4",
This is a issue that comes from "decompress-unzip" package

![image](https://github.com/SonarSource/sonar-scanner-npm/assets/127343078/40d4f937-5251-4cef-8f45-80aa4db5e3dd)

**Comment by alexander-kamushkin-sonarsource** [comment]
Thanks a lot - we will look at it!

**Comment by victor-diez-sonarsource** [comment]
Hi @alexvarelaAA,

sorry, but I cannot reproduce this. Is `file-type` a global package that you've installed locally? I  don't see it anywhere in our dependency tree.

**Comment by alexvarelaAA** [comment]
Hi @victor-diez-sonarsource, thanks for answered me. The issue is caused when I override the package "file-type": "^16.5.4" to its latest version. This was something required by our Security Team but look into the nest dependencies tree I saw that the issue comes from "decompress" packages that you are using to unzip, untar, etc., the files. The issue comes from that side so is not a issue for your side. I already create a Issue in the Decompress github, so I will proceed to close this one. Thank you for your help.

![image](https://github.com/SonarSource/sonar-scanner-npm/assets/127343078/0defcd29-9e6d-4c04-932f-2c1abe716427)
![image](https://github.com/SonarSource/sonar-scanner-npm/assets/127343078/0894ad38-c30b-4f12-94a5-0c3ad493724f)
