### ISSUE TITLE
Java 11 being deprecated, we should update the CLI scanner version

### ISSUE THREAD

**Issue by gabriel-vivas-sonarsource** [SonarSource/sonar-scanner-npm#52]
Java 11 is being deprecated for the scanners.
We should update the CLI scanner version.

See Community post:
https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597

See relevant line:
https://github.com/SonarSource/sonar-scanner-npm/blob/master/src/config.js#L33

**Comment by agigleux** [comment]
I think you should also look at this line: https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/.cirrus/nodejs.Dockerfile#L10

**Comment by eb-g3dg5** [comment]
Is this planned to be done prior to the date in the notice (October 31, 2023)?

**Comment by agigleux** [comment]
For sure this will be handled before the 31st of October 2023.

**Comment by victor-diez-sonarsource** [comment]
Fixed by https://github.com/SonarSource/sonar-scanner-npm/pull/53
