### ISSUE TITLE
Add compatibility for people using sonar-scanner

### ISSUE THREAD

**Issue by Neizan93** [SonarSource/sonar-scanner-npm#63]
Some teams still use https://www.npmjs.com/package/sonar-scanner with a sonar-project.properties in local
and overwriting some properties in package.json script.
Please add compatibility to easy migrate to official.

**Comment by yassin-kammoun-sonarsource** [comment]
Hello @Neizan93,

Thank you once again for bringing this matter to our attention.

We have thoroughly reviewed the NPM project you referenced. Upon evaluation, we found that the functionality offered by this project is already encompassed within our sonar-scanner-npm tool.

Given this, the transition to our tool should be seamless and efficient. We encourage you to explore its features and capabilities. Should you encounter any missing use cases or have any further queries, please do not hesitate to let us know.

Cheers!
