### ISSUE TITLE
CLI arguments and local scanner no more supported

### ISSUE THREAD

**Issue by BBE78** [SonarSource/sonar-scanner-npm#91]
Since https://github.com/SonarSource/sonar-scanner-npm/pull/55 refactoring, the command line arguments and the local scanner are no more taken into account.

**Comment by BBE78** [comment]
Proposed solution: in the "`index.js`" file, replace the line #45 of the function `scanWithCallback`
```javascript
  scan(params).then(() => {
```
by
```javascript
  scan(params, cliArgs, localScanner).then(() => {
```

**Comment by vdiez** [comment]
Hello @BBE78,

thank you for reporting this. We'll handle this for next release.

**Comment by BBE78** [comment]
Thank you !
