### ISSUE TITLE
[Feature Request]: Caching plugin downloads

### ISSUE THREAD

**Issue by monwolf** [SonarSource/sonar-scanner-npm#92]
Hi,

We are using this package in our CI/CD system inside a docker nightly built. So every time we run SonarQube scanner, it downloads all plugins from our sonar instance ~250Mb. Sonar is deployed in an external network with reduced BW so it spends some time downloading all the plugins in every build. 

Could we implement some kind of caching for this? 

Thanks.

**Comment by ilia-kebets-sonarsource** [comment]
Hello monwolf,

The scanner caches the download of the analyzers in `~/.sonar/`, you can customize the location with the `SONAR_USER_HOME` environment variable.
