### ISSUE TITLE
Please update sonar.branch to sonar.branch.name

### ISSUE THREAD

**Issue by ricochetbrown** [SonarSource/sonar-scanner-npm#93]
We have a need with nx to use sonar.branch.name because ADO uses a detached HEAD. Could you please update sonar.branch to sonar.branch.name so we can use the SONAR_BRANCH env variable?

**Comment by ricochetbrown** [comment]
sonar.branch is deprecated

**Comment by ilia-kebets-sonarsource** [comment]
Hello @ricochetbrown,

Could you clarify your request? I don't understand.

**Comment by saberduck** [comment]
@ricochetbrown how exactly does this value in the test file affect you? To me it looks like just a test fixture, we actually don't have any logic around this property
